OrdererOrgs:
  - Name: Orderer
    Domain: doc-app.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: allparticipants
   Domain: allparticipants.doc-app.com
   EnableNodeOUs: true
   Template:
      Count: 3
   Users:
      Count: 3
